### ISSUE TITLE
Typo in wiki page CentOS 7 1611 Minimal x86_64 Base Installation Guide

### ISSUE THREAD

**Issue by a-roussos** [rharmonson/richtech#10]
Hi @rharmonson. Just came across your wiki "CentOS 7 1611 Minimal x86_64 Base Installation Guide" and found it very informative. Spotted a small typo in section 19 (VM Template) -- the 'cut+paste' segment that contains the commands for `sealvm.sh` contains the following line:

`rm -f /etc/ssh/ssh_host_rm -rf /root/.ssh/`

I believe it should be like this instead:

`rm -f /etc/ssh/ssh_host_*`
`rm -rf /root/.ssh/`

**Comment by rharmonson** [comment]
You are absolutely correct. Thank you! Corrected.

I may be moving to Jeckyll soon with the guides so check back and provide comments.
