### ISSUE TITLE
The Disable IPv6 section seems unclear. Still appears to disable for "all".

### ISSUE THREAD

**Issue by botsmack** [rharmonson/richtech#15]
In the [Disable IPv6 section of CentOS 7 1611 Minimal x86_64 Base Installation Guide](https://github.com/rharmonson/richtech/wiki/CentOS-7-1611-Minimal-x86_64-Base-Installation-Guide#disable-ipv6), you state that you edited it so it would not disable it everywhere, but rather just disable per interface only. However, in the example for per interface, you still have the option set for "all" being disabled:

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
```

Shouldn't the first line be removed and only be the single entry for the example interface?

```
net.ipv6.conf.eth0.disable_ipv6 = 1
```

The disable for everywhere option seems correct. You show the options for disabling "all" and "by default":

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```

It seems that the first section where you disable per interface only, it should have that line (`net.ipv6.conf.all.disable_ipv6`) removed. Or am I misreading it?

**Comment by rharmonson** [comment]
Botsmack,

I agree it is wrong and needs to be revised.

I have had, essentially, three past revisions on ipv6.

1. No IPv6! Don't load the IPv6 kernel module
2. Load the IPv6 kernel module but no IPv6 on interfaces <--- application X required kernel module
3. Load the IPv6 kernel module but no IPv6 on interfaces except ::1 <-- application Y required ::1

Revising now with your suggestion and some.. done!

https://github.com/rharmonson/richtech/wiki/CentOS-7-1611-Minimal-x86_64-Base-Installation-Guide#disable-ipv6

If it is unclear or whatever, I want your feedback. Let me know.

I am revising the document in its entirety and hope to release the "Final" in the next couple of months at rharmonson.github.io for CentOS 7.4.

Thank you!

Richard

**Comment by botsmack** [comment]
Awesome! Looks good from here. Just wanted to let you know, this resource has been a big help for getting a baseline image up and running. Looking forward to the 7.4 revision.

**Comment by rharmonson** [comment]
botsmack,

Here is the newest revision of the CentOS 7 Installation Guide.

https://rharmonson.github.io/cos7inst.html

No real surprises here but I did change the firewall policy process in hopes of informing folks on iptables-restore and iptables-save. Also, warning on cloud-init  0.7.9 as it is BROKEN! Steamy pile of $hit! I am undecided on waiting for the fix release and revise or revise and provide guidance on installing from the development branch. Do you have an opinion?

If you have an opportunity, please read through it and call out typos or my non-linear ramblings. If you don't have the time, not a problem. We all have busy schedules.

I appreciate your help!

Richard

**Comment by rharmonson** [comment]
Closing Issue.
