### ISSUE TITLE
Significant typo in wiki

### ISSUE THREAD

**Issue by wagnered** [rharmonson/richtech#17]
Very good installation wiki for Centos 7 and Ampache.
I believe I found a typo in the wiki:
> yum-config-manager --enable remi-php56

The first hyphen should be a space if the yum command is the same on centos as it is on any other RH based system.

If the Ampache release is installed, installation of Composer isn't necessary. Also .htaccess has already been created.

I would like to suggest that this information is included in the wiki.

**Comment by rharmonson** [comment]
Thank you for opening the issue.

I have corrected the typo and added your comment regarding composer and .htaccess. Since I have not done a new installation to verify, not removed the potential erroneous information. I still use Ampache so it just a matter of time.
