### ISSUE TITLE
User without Domain

### ISSUE THREAD

**Issue by fpieressa** [rharmonson/richtech#18]
Hi, good job!! One question, following your example, you are using "richard@2factor.net" as the user domain username, is there any way to configure freeradius to don't need the add of the domain to the username (so use "richard" as the username)?

Thanks!

**Comment by rharmonson** [comment]
FreeRADIUS can be configured to do pretty much anything if you dig deep enough or can stomach the trolls on FreeRADIUS forums. I suspect you could locate a "default" value in its configuration. However, if you are using a directory service and SSSD (Kerberos), there will be additional challenges.

Sorry if not terribly helpful, but if you develop a solution that will improve the "how to" feel free to fork and provide a revision for review and merge.

**Comment by fpieressa** [comment]
Hi Richard, we have solved it adding in the /etc/raddb/hints the following entries:

DEFAULT User-Name !~ ".*@"
     User-Name := "%{User-Name}@2factor.net"

Thanks for your time!

**Comment by rharmonson** [comment]
Nice and well done! On next revision, I will add your example as a note.
