### ISSUE TITLE
on centos minimal on rpi, size resize will cause internet to become on/off from time to time

### ISSUE THREAD

**Issue by deya-eldeen** [rharmonson/richtech#19]
what solved this for me was a simple

**yum update**

https://github.com/rharmonson/richtech/wiki/Using-CentOS-7.2.1511-Minimal-on-the-Raspberry-PI-3

**Comment by rharmonson** [comment]
Good to know they fixed it. Next revision, I will verify and update the article.

Thank you and I appreciate you contributing!

Richard
