### ISSUE TITLE
images for centos7 google auth

### ISSUE THREAD

**Issue by rharmonson** [rharmonson/richtech#2]
![gauth](https://cloud.githubusercontent.com/assets/7966126/7761484/365419ae-ffdb-11e4-9bad-4aa043d2c427.jpg)

**Comment by alegram** [comment]
after clean install, and radius config checking in debug mode with command:
 **radiusd -X**


**there is an error:**
/etc/raddb/mods-config/files/authorize[65]: Parse error (check) for entry Reply-Message: Invalid attribute name
Failed reading /etc/raddb/mods-config/files/authorize
/etc/raddb/mods-enabled/files[9]: Instantiation failed for module "files"


i m looking it up...

**Comment by lailtonmontenegro** [comment]
can anyone help with it? I have the same problem.
