### ISSUE TITLE
Softether vpn: grep command not found.

### ISSUE THREAD

**Issue by dbaflight** [rharmonson/richtech#3]
After this came out at the first time, i installed grep by: yum install grep. However, this error message still come out.

**Comment by rharmonson** [comment]
dbaflight,

The only place in the article I use grep is at the section found at the URL given below:

https://github.com/rharmonson/richtech/wiki/Installing-SoftEther-VPN-4-on-CentOS-6.5-Minimal-x86_64#enable-init-script--start-softether

You should not need to install grep for it is installed as part of the base (minimal) operating system. Or did you use a different Linux distribution or installation method from the one described here:

https://github.com/rharmonson/richtech/wiki/CentOS-6.5-Minimal-x86_64-Base-Installation-Guide

Please clarify by providing additional information if you still need further assistance. I would like to help but need more details.

R

**Comment by dbaflight** [comment]
Thanks for your reply and your valuable time!
There's additional information:

root@001 vpnserver]# make
"grep" command not found.
Installation is aborted.
make: **\* [default] Error 1
[root@001 vpnserver]#

I am using Centos 6.7

**Comment by rharmonson** [comment]
Odd. Please execute the following two commands.

1
Please provide me your path environmental variable using "# echo $PATH" then copy and paste the results.

Here is an example from one of my hosts. Yours may differ.

[root@ns ~]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
[root@ns ~]#

2
Execute "# rpm -qi grep" and verify you don't get 'package X is not installed.' From your earlier communication, you did a yum to install which would imply it is installed now, but the oddity is it wasn't. It should have already been installed.

Next Steps
If you $PATH looks good and grep is installed then we have two options. I could install 6.7 and walk through my guide and try to reproduce the error. The second option is to create a new guide using CentOS 7 (1503). If I am going to take the time, I rather spend it on CentOS 7. Do you have access to the CentOS 7 (1503-1) Minimal installation media?

R

**Comment by dbaflight** [comment]
Thanks for your reply.

[root@001 ~]# echo $PATH
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
[root@001 ~]# rpm -qi grep
Name        : grep                         Relocations: (not relocatable)
Version     : 2.20                              Vendor: CentOS
Release     : 3.el6_7.1                     Build Date: Tue Nov 10 17:52:52 201
Install Date: Mon Nov 23 22:06:14 2015         Build Host: c6b9.bsys.dev.centosorg
Group       : Applications/Text             Source RPM: grep-2.20-3.el6_7.1.srcrpm
Size        : 1197808                          License: GPLv3+
Signature   : RSA/SHA1, Tue Nov 10 20:40:47 2015, Key ID 0946fca2c105b9de
Packager    : CentOS BuildSystem http://bugs.centos.org
URL         : http://www.gnu.org/software/grep/
Summary     : Pattern matching utilities
Description :
The GNU versions of commonly used grep utilities. Grep searches through
textual input for lines which contain a match to a specified pattern and then
prints the matching lines. GNU's grep utilities include grep, egrep and fgrep.

GNU grep is needed by many scripts, so it shall be installed on every system

---

Actually i am using a vps so i can simply reinstall the system.

**Comment by rharmonson** [comment]
OK. So for my benefit please share with me the installation process. For example, do you upload and attach media (ISO), netinstall, or does the VPS provider provide media (which?) and install or do they provide a base operating system to you for installing packages, configuration, etc? Do you understand my concern? If you are not using the CentOS Minimum installation media, authoring a CentOS 7 guide is not likely to resolve the problem. It might, but probably not. If the VPS is providing a base OS to you for use, then opening a service ticket with the VPS describing the issue may be an option.

I am not brushing you off on to your VPS! I do want to assist, but your operating environment is an unknown to me. Who is your VPS provider? Maybe they have a free trial I could take a peek at to potentially reproduce you symptoms.

R

**Comment by dbaflight** [comment]
The problem is solved. I opened a ticket in order to asked about this grep problem, and they gave me an answer. They said they have updated the centos6.7 ISO so I should reinstall the system. After reinstalling centos6.7, this problem is solved, everything works well. It seems that it is the idc's problem, not ours.
Thank you again for your kind help.

**Comment by rharmonson** [comment]
Awesome!

I am glad your VPS got it fixed. I will be building a new lab in 2016 and posting an updated CentOS 7 and SoftEther guide at some point. Please star and follow my github if you found it helpful.

Best wishes,

R

**Comment by shaunie2fly** [comment]
Just for sake of closure i found out the issue here.

The command **where** determines whether the grep command is available.  If the **where** tool isn't installed you get the `"grep" command not found.` when running make from the source folder.

just `yum install where`  ;)

**Comment by danuid** [comment]
Thanks to @shaunie2fly , I found out that for my CentOS 7, `yum install which` fixed the problem.

**Comment by cyberguroo** [comment]
@danuid Thanks, had been pulling my hairs for so long, phew, finally got that working thanks to your suggestion. :)

**Comment by rharmonson** [comment]
Interesting. I have not ran into this problem, myself. Be nice to know if the OS installations where from media or a service provider. Also, what media or service provider? I suspect the botched installation are from providers not media, but..

**Comment by cyberguroo** [comment]
@rharmonson  Thanks for asking, I guess it has something to do with the "minimal" part of the OS which in my example was "centos-7-x86_64-minimal" _which_ most probably didn't have the `which` command. Its apparent that this command is being used directly/indirectly during the `make` process. Since this command was lacking from the OS, installing it manually solved the aforementioned issue.

**Comment by rharmonson** [comment]
I appreciate you sharing the challenge.

If you are curioius, I just now completed several installs in the last 48 hours for unrelated projects using CentOS 7 minimal or CentOS 7 netinstall media. Without installing additional packages, I executed `# rpm -qi which` and got the following:

```
[root@ipa1 ~]# rpm -qi which
Name        : which
Version     : 2.20
Release     : 7.el7
Architecture: x86_64
Install Date: Sat 25 Feb 2017 06:07:21 PM PST
Group       : Applications/System
Size        : 76962
License     : GPLv3
Signature   : RSA/SHA256, Thu 03 Jul 2014 10:43:07 PM PDT, Key ID 24c6a8a7f4a80eb5
Source RPM  : which-2.20-7.el7.src.rpm
Build Date  : Mon 09 Jun 2014 07:25:22 PM PDT
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://www.xs4all.nl/~carlo17/which/
Summary     : Displays where a particular program in your path is located
Description :
The which command shows the full pathname of a specified program, if
the specified program is in your PATH.

```

The package is installed by default. Obviously, several of you have reported the problem so I have updated the most current SoftEther VPN Guide to call out the dependency to compile with `make`. If you did not install CentOS 7 yourself, perhaps your provider was removing packages that they felt were unessential?

Updated guide with the note is found here:

https://github.com/rharmonson/richtech/wiki/OSVDC-Series:-Secure-Remote-Access-with-SoftEther-VPN-Server-and-Client-4.2#install-softether-vpn-servr

Thank you!
