### ISSUE TITLE
What happen to your NSX Lab Series.

### ISSUE THREAD

**Issue by tmitchell5280** [rharmonson/richtech#4]
I used these are wanted to recheck some configurations.

These were very helpful.

Thanks,

**Comment by rharmonson** [comment]
Wow! Good to know someone was using them. I removed them due to being incomplete and estimating my chance to return to the project as slim to none. Besides, I felt embarrassed posting woefully incomplete documentation.

I am reasonably certain I kept a backup. Did you need specific article(s) in the series or all of them? I will get them back on the wiki for you and apologize for the inconvenience.

Richard

**Comment by tmitchell5280** [comment]
Hi Richard,

That would be great. Can you add the series back and maybe I can help you with making sure that they are correct and updated.

Thanks again,

-Troy

Sent from Outlook Mobile

On Fri, Jan 8, 2016 at 11:08 PM -0800, "RHarmonson" notifications@github.com wrote:

Wow! Good to know someone was using them. I removed them due to being incomplete and estimating my chance to return to the project as slim to none. Besides, I felt embarrassed posting woefully incomplete documentation.

I am reasonably certain I kept a backup. Did you need specific article(s) in the series or all of them? I will get them back on the wiki for you and apologize for the inconvenience.

Richard

**Comment by rharmonson** [comment]
Sounds good. I would love to have a contributor on the series.

I am in the process of moving my workstation and development environment into a new room. I should be done in the next forty-eight hours. After that is done, I will repost the series, so check back Monday evening.

**Comment by tmitchell5280** [comment]
Thank you!

-Troy

Sent from Outlook Mobile

On Sat, Jan 9, 2016 at 4:47 PM -0800, "RHarmonson" notifications@github.com wrote:

Sounds good. I would love to have a contributor on the series.

I am in the process of moving my workstation and development environment into a new room. I should be done in the next forty-eight hours. After that is done, I will repost the series, so check back Monday evening.

**Comment by rharmonson** [comment]
You are not forgotten! Just finished with the workstation move into my new workspace. I am a tired and will not post until tomorrow night, but I did want to let you know that I have not forgotten you. Night.

**Comment by rharmonson** [comment]
I have reverted/recovered the posts.

**Comment by tmitchell5280** [comment]
Thanks Richard. 

I will review and let you know of any changes that I think we might need to keep these documents updated. 

-Troy 

----- Original Message -----

**Comment by rharmonson** [comment]
Sounds good. I will close this issue but we can open another for edits or come up with another strategy. Contributor?

Have a good day and thank you for opening an issue asking for reposting of the series.

R
