### ISSUE TITLE
Tool used for Diagrams

### ISSUE THREAD

**Issue by gitkalz** [rharmonson/richtech#8]
Hello Richard,

Thanks for sharing wealth of well structured knowledge.. 

I am curious to ask how did you create this following simple yet elegant diagram 

![Network](https://cloud.githubusercontent.com/assets/7966126/13108554/b0beaf10-d528-11e5-9422-60dc1b9b55a1.jpg) 

I would like to use your styling to convey simple typologies. Please elaborate or link to the method.

**Comment by rharmonson** [comment]
Hello Kalzi!

I used Visio 2013 and created a customized stencil by utilizing existing icons, mostly, that I edited by subtracting and adding stuff. Visio has a built-in stencil editor. It took an embarrassing amount of time to create it. (Notice I don't say how long.) You are welcome to use it. Also, providing my template.

Visio 2013 Template
https://drive.google.com/open?id=0Bx6goS4_X3kPQ09xNjRjVENrVkE

Visio 2013 Stencil
https://drive.google.com/open?id=0Bx6goS4_X3kPYkQ4Z2VkM2RaNEE

After opening the template, you will need to select "More Shapes" then "Open Stencil."

If you do not have Visio, LibreOffice Draw is an alternative, but the above files are not supported (to my knowledge). Visio is one of the few Micro$oft products I still use outside of work.

Lastly, I use Gimp on either Linux or Windows for touch ups prior to publishing.

If my contributions are worthy, please "Star" me. It is a small thing but the feedback keeps me posting.
(Never mind! I see you did already. Thank you!)

**Comment by gitkalz** [comment]
Richard,

Thank you very much for sharing your work.. I will surely try out your templates.  BTW, I really like your posts and the way you structure the information. I understand that these posts take considerable amount of your time, but they are helping people like us to have a perspective on evaluation and implementation of complex architectures.

Keep up with your good work and Thank you :+1:
